In [113]:
import pandas as pd
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# define input string
data = 'hello world'
print(data)
# define universe of possible input values
alphabet = 'abcdefghijklmnopqrstuvwxyz '
# define a mapping of chars to integers
char_to_int = dict((c, i) for i, c in enumerate(alphabet))
int_to_char = dict((i, c) for i, c in enumerate(alphabet))
# integer encode input data
integer_encoded = [char_to_int[char] for char in data]
print(integer_encoded)
# one hot encode
onehot_encoded = list()
for value in integer_encoded:
    letter = [0 for _ in range(len(alphabet))]
    letter[value] = 1
    onehot_encoded.append(letter)
print(onehot_encoded)
# invert encoding
inverted = int_to_char[argmax(onehot_encoded[0])]
print(inverted)

hello world
[7, 4, 11, 11, 14, 26, 22, 14, 17, 11, 3]
[[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
h


In [119]:
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
print(data)

pd.get_dummies(data)

['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']


cold  hot  warm
0     1    0     0
1     1    0     0
2     0    0     1
3     1    0     0
4     0    1     0
5     0    1     0
6     0    0     1
7     1    0     0
8     0    0     1
9     0    1     0

In [132]:

# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
print(data)

#encoding categories
data= label_encoder.fit_transform(data)
print(data)

['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
[0 0 2 0 1 1 2 0 2 1]


In [133]:
ohe = OneHotEncoder(sparse=True) # Will return sparse matrix if set True else will return an array.
data = data.reshape(len(data), 1)
ohe= onehot_encoder.fit_transform(data) 
print(ohe)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [138]:
# invert first example
inverted = label_encoder.inverse_transform([argmax(ohe[5:])]) # Convert the data back to the original representation.
print(inverted)

['hot']


In [85]:
df=pd.read_csv('amazon.csv')
df

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Class  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [86]:
df.Author.value_counts()

Jeff Kinney                           12
Rick Riordan                          11
Gary Chapman                          11
Suzanne Collins                       11
American Psychological Association    10
                                      ..
Randall Munroe                         1
Golden Books                           1
Charles Krauthammer                    1
Chrissy Teigen                         1
Mike Moreno                            1
Name: Author, Length: 248, dtype: int64

In [87]:
df.shape

(550, 7)

In [88]:
pd.get_dummies(df.Author)

Abraham Verghese  Adam Gasiewski  Adam Mansbach  Adir Levy  \
0                   0               0              0          0   
1                   0               0              0          0   
2                   0               0              0          0   
3                   0               0              0          0   
4                   0               0              0          0   
..                ...             ...            ...        ...   
545                 0               0              0          0   
546                 0               0              0          0   
547                 0               0              0          0   
548                 0               0              0          0   
549                 0               0              0          0   

     Admiral William H. McRaven  Adult Coloring Book Designs  Alan Moore  \
0                             0                            0           0   
1                             0                            0           0   
2                             0                            0           0   
3                             0                            0           0   
4                             0                            0           0   
..                          ...                          ...         ...   
545                           0                            0           0   
546                           0                            0           0   
547                           0                            0           0   
548                           0                            0           0   
549                           0                            0           0   

     Alex Michaelides  Alice Schertle  Allie Brosh  ...  Todd Burpo  \
0                   0               0            0  ...           0   
1                   0               0            0  ...           0   
2                   0               0            0  ...           0   
3                   0               0            0  ...           0   
4                   0               0            0  ...           0   
..                ...             ...          ...  ...         ...   
545                 0               0            0  ...           0   
546                 0               0            0  ...           0   
547                 0               0            0  ...           0   
548                 0               0            0  ...           0   
549                 0               0            0  ...           0   

     Tony Hsieh  Tucker Carlson  Veronica Roth  W. Cleon Skousen  \
0             0               0              0                 0   
1             0               0              0                 0   
2             0               0              0                 0   
3             0               0              0                 0   
4             0               0              0                 0   
..          ...             ...            ...               ...   
545           0               0              0                 0   
546           0               0              0                 0   
547           0               0              0                 0   
548           0               0              0                 0   
549           0               0              0                 0   

     Walter Isaacson  William Davis  William P. Young  Wizards RPG Team  \
0                  0              0                 0                 0   
1                  0              0                 0                 0   
2                  0              0                 0                 0   
3                  0              0                 0                 0   
4                  0              0                 0                 0   
..               ...            ...               ...               ...   
545                0              0                 0                 0   
546              

In [89]:
pd.get_dummies(df)

User Rating  Reviews  Price  Year  Name_10-Day Green Smoothie Cleanse  \
0            4.7    17350      8  2016                                   1   
1            4.6     2052     22  2011                                   0   
2            4.7    18979     15  2018                                   0   
3            4.7    21424      6  2017                                   0   
4            4.8     7665     12  2019                                   0   
..           ...      ...    ...   ...                                 ...   
545          4.9     9413      8  2019                                   0   
546          4.7    14331      8  2016                                   0   
547          4.7    14331      8  2017                                   0   
548          4.7    14331      8  2018                                   0   
549          4.7    14331      8  2019                                   0   

     Name_11/22/63: A Novel  Name_12 Rules for Life: An Antidote to Chaos  \
0                         0                                             0   
1                         1                                             0   
2                         0                                             1   
3                         0                                             0   
4                         0                                             0   
..                      ...                                           ...   
545                       0                                             0   
546                       0                                             0   
547                       0                                             0   
548                       0                                             0   
549                       0                                             0   

     Name_1984 (Signet Classics)  \
0                              0   
1                              0   
2                              0   
3                              1   
4                              0   
..                           ...   
545                            0   
546                            0   
547                            0   
548                            0   
549                            0   

     Name_5,000 Awesome Facts (About Everything!) (National Geographic Kids)  \
0                                                    0                         
1                                                    0                         
2                                                    0                         
3                                                    0                         
4                                                    1                         
..                                                 ...                         
545                                                  0                         
546                                                  0                         
547                                                  0                         
548                                                  0                         
549                                                  0                         

     Name_A Dance with Dragons (A Song of Ice and Fire)  ...  \
0                                                    0   ...   
1                                                    0   ...   
2                                                    0   ...   
3                                                    0   ...   
4                                                    0   ...   
..                                                 ...   ...   
545                                                  0   ...   
546                                                  0   ...   
547                                                  0   ...   
548                                                  0   ...   
549                                          

In [90]:
pd.get_dummies(df).shape

(550, 605)

In [91]:
le= LabelEncoder()

In [93]:
df.Author=le.fit_transform(df.Author)

In [95]:
df.Name=le.fit_transform(df.Name)

In [96]:
df

Name  Author  User Rating  Reviews  Price  Year        Class
0       0     114          4.7    17350      8  2016  Non Fiction
1       1     219          4.6     2052     22  2011      Fiction
2       2     134          4.7    18979     15  2018  Non Fiction
3       3      95          4.7    21424      6  2017      Fiction
4       4     174          4.8     7665     12  2019  Non Fiction
..    ...     ...          ...      ...    ...   ...          ...
545   349     120          4.9     9413      8  2019      Fiction
546   350     121          4.7    14331      8  2016  Non Fiction
547   350     121          4.7    14331      8  2017  Non Fiction
548   350     121          4.7    14331      8  2018  Non Fiction
549   350     121          4.7    14331      8  2019  Non Fiction

[550 rows x 7 columns]

In [75]:
df=pd.read_csv('countries.csv')
df

country  year  population
0     Afghanistan  1952     8425333
1     Afghanistan  1957     9240934
2     Afghanistan  1962    10267083
3     Afghanistan  1967    11537966
4     Afghanistan  1972    13079460
...           ...   ...         ...
1699     Zimbabwe  1987     9216418
1700     Zimbabwe  1992    10704340
1701     Zimbabwe  1997    11404948
1702     Zimbabwe  2002    11926563
1703     Zimbabwe  2007    12311143

[1704 rows x 3 columns]

In [76]:
x=pd.get_dummies(df.country)
x

Afghanistan  Albania  Algeria  Angola  Argentina  Australia  Austria  \
0               1        0        0       0          0          0        0   
1               1        0        0       0          0          0        0   
2               1        0        0       0          0          0        0   
3               1        0        0       0          0          0        0   
4               1        0        0       0          0          0        0   
...           ...      ...      ...     ...        ...        ...      ...   
1699            0        0        0       0          0          0        0   
1700            0        0        0       0          0          0        0   
1701            0        0        0       0          0          0        0   
1702            0        0        0       0          0          0        0   
1703            0        0        0       0          0          0        0   

      Bahrain  Bangladesh  Belgium  ...  Uganda  United Kingdom  \
0           0           0        0  ...       0               0   
1           0           0        0  ...       0               0   
2           0           0        0  ...       0               0   
3           0           0        0  ...       0               0   
4           0           0        0  ...       0               0   
...       ...         ...      ...  ...     ...             ...   
1699        0           0        0  ...       0               0   
1700        0           0        0  ...       0               0   
1701        0           0        0  ...       0               0   
1702        0           0        0  ...       0               0   
1703        0           0        0  ...       0               0   

      United States  Uruguay  Venezuela  Vietnam  West Bank and Gaza  \
0                 0        0          0        0                   0   
1                 0        0          0        0                   0   
2                 0        0          0        0                   0   
3                 0        0          0        0                   0   
4                 0        0          0        0                   0   
...             ...      ...        ...      ...                 ...   
1699              0        0          0        0                   0   
1700              0        0          0        0                   0   
1701              0        0          0        0                   0   
1702              0        0          0        0                   0   
1703              0        0          0        0                   0   

      Yemen, Rep.  Zambia  Zimbabwe  
0               0       0         0  
1               0       0         0  
2               0       0         0  
3               0       0         0  
4               0       0         0  
...           ...     ...       ...  
1699            0       0         1  
1700            0       0         1  
1701            0       0         1  
1702            0       0         1  
1703            0       0         1  

[1704 rows x 142 columns]

In [77]:
data=pd.concat([df,x], axis='columns')
data

country  year  population  Afghanistan  Albania  Algeria  Angola  \
0     Afghanistan  1952     8425333            1        0        0       0   
1     Afghanistan  1957     9240934            1        0        0       0   
2     Afghanistan  1962    10267083            1        0        0       0   
3     Afghanistan  1967    11537966            1        0        0       0   
4     Afghanistan  1972    13079460            1        0        0       0   
...           ...   ...         ...          ...      ...      ...     ...   
1699     Zimbabwe  1987     9216418            0        0        0       0   
1700     Zimbabwe  1992    10704340            0        0        0       0   
1701     Zimbabwe  1997    11404948            0        0        0       0   
1702     Zimbabwe  2002    11926563            0        0        0       0   
1703     Zimbabwe  2007    12311143            0        0        0       0   

      Argentina  Australia  Austria  ...  Uganda  United Kingdom  \
0             0          0        0  ...       0               0   
1             0          0        0  ...       0               0   
2             0          0        0  ...       0               0   
3             0          0        0  ...       0               0   
4             0          0        0  ...       0               0   
...         ...        ...      ...  ...     ...             ...   
1699          0          0        0  ...       0               0   
1700          0          0        0  ...       0               0   
1701          0          0        0  ...       0               0   
1702          0          0        0  ...       0               0   
1703          0          0        0  ...       0               0   

      United States  Uruguay  Venezuela  Vietnam  West Bank and Gaza  \
0                 0        0          0        0                   0   
1                 0        0          0        0                   0   
2                 0        0          0        0                   0   
3                 0        0          0        0                   0   
4                 0        0          0        0                   0   
...             ...      ...        ...      ...                 ...   
1699              0        0          0        0                   0   
1700              0        0          0        0                   0   
1701              0        0          0        0                   0   
1702              0        0          0        0                   0   
1703              0        0          0        0                   0   

      Yemen, Rep.  Zambia  Zimbabwe  
0               0       0         0  
1               0       0         0  
2               0       0         0  
3               0       0         0  
4               0       0         0  
...           ...     ...       ...  
1699            0       0         1  
1700            0       0         1  
1701            0       0         1  
1702            0       0         1  
1703            0       0         1  

[1704 rows x 145 columns]

In [78]:
final_data=data.drop(['country'], axis='columns')
final_data

year  population  Afghanistan  Albania  Algeria  Angola  Argentina  \
0     1952     8425333            1        0        0       0          0   
1     1957     9240934            1        0        0       0          0   
2     1962    10267083            1        0        0       0          0   
3     1967    11537966            1        0        0       0          0   
4     1972    13079460            1        0        0       0          0   
...    ...         ...          ...      ...      ...     ...        ...   
1699  1987     9216418            0        0        0       0          0   
1700  1992    10704340            0        0        0       0          0   
1701  1997    11404948            0        0        0       0          0   
1702  2002    11926563            0        0        0       0          0   
1703  2007    12311143            0        0        0       0          0   

      Australia  Austria  Bahrain  ...  Uganda  United Kingdom  United States  \
0             0        0        0  ...       0               0              0   
1             0        0        0  ...       0               0              0   
2             0        0        0  ...       0               0              0   
3             0        0        0  ...       0               0              0   
4             0        0        0  ...       0               0              0   
...         ...      ...      ...  ...     ...             ...            ...   
1699          0        0        0  ...       0               0              0   
1700          0        0        0  ...       0               0              0   
1701          0        0        0  ...       0               0              0   
1702          0        0        0  ...       0               0              0   
1703          0        0        0  ...       0               0              0   

      Uruguay  Venezuela  Vietnam  West Bank and Gaza  Yemen, Rep.  Zambia  \
0           0          0        0                   0            0       0   
1           0          0        0                   0            0       0   
2           0          0        0                   0            0       0   
3           0          0        0                   0            0       0   
4           0          0        0                   0            0       0   
...       ...        ...      ...                 ...          ...     ...   
1699        0          0        0                   0            0       0   
1700        0          0        0                   0            0       0   
1701        0          0        0                   0            0       0   
1702        0          0        0                   0            0       0   
1703        0          0        0                   0            0       0   

      Zimbabwe  
0            0  
1            0  
2            0  
3            0  
4            0  
...        ...  
1699         1  
1700         1  
1701         1  
1702         1  
1703         1  

[1704 rows x 144 columns]

In [79]:
le = LabelEncoder()

In [80]:
df.country=le.fit_transform(df.country)

In [81]:
df

country  year  population
0           0  1952     8425333
1           0  1957     9240934
2           0  1962    10267083
3           0  1967    11537966
4           0  1972    13079460
...       ...   ...         ...
1699      141  1987     9216418
1700      141  1992    10704340
1701      141  1997    11404948
1702      141  2002    11926563
1703      141  2007    12311143

[1704 rows x 3 columns]